import 'package:food_ui/Services/CartService/ICartService.dart';

class CartService implements ICartSevice {
  @override
  Future<List<Map<String, dynamic>>> getAllProducts() async {
    return [
      {
        "id": 1,
        "image": "item1.png",
        "name": "Veggie mix",
        "price": 200,
        "category": "Foods",
        "description": "Veggie tomato mix",
      },
      {
        "id": 2,
        "image": "item2.png",
        "name": "Chicken",
        "price": 250,
        "category": "Foods",
        "description": "Chicken with mint",
      },
      {
        "id": 3,
        "image": "item3.png",
        "name": "Spicy fish",
        "price": 600,
        "category": "Foods",
        "description": "Spicy fish sauce",
      },
      {
        "id": 4,
        "image": "item4.png",
        "name": "Moi-moi.",
        "price": 900,
        "category": "Foods",
        "description": "Moi-moi and ekpa.",
      },
      {
        "id": 5,
        "image": "item5.png",
        "name": "Chicken Fry",
        "price": 400,
        "category": "Foods",
        "description": "Fried chicken m.",
      },
      {
        "id": 6,
        "image": "item6.png",
        "name": "Coke",
        "price": 400,
        "category": "Drinks",
        "description": "Coke",
      },
      {
        "id": 7,
        "image": "item7.png",
        "name": "Fanta",
        "price": 400,
        "category": "Drinks",
        "description": "Fanta",
      },
      {
        "id": 8,
        "image": "item8.png",
        "name": "Sprite",
        "price": 400,
        "category": "Drinks",
        "description": "Sprite",
      },
      {
        "id": 9,
        "image": "item6.png",
        "name": "Pepsi",
        "price": 400,
        "category": "Drinks",
        "description": "Pepsi",
      },
      {
        "id": 10,
        "image": "item10.png",
        "name": "Water",
        "price": 30,
        "category": "Drinks",
        "description": "Water",
      },
      {
        "id": 11,
        "image": "item11.png",
        "name": "Biscuits",
        "price": 30,
        "category": "Snacks",
        "description": "Biscuits",
      },
      {
        "id": 12,
        "image": "item12.png",
        "name": "Cookies",
        "price": 30,
        "category": "Snacks",
        "description": "Cookies",
      },
      {
        "id": 13,
        "image": "item13.png",
        "name": "Sandwitch",
        "price": 30,
        "category": "Snacks",
        "description": "Sandwitch",
      },
      {
        "id": 14,
        "image": "item14.png",
        "name": "Burger",
        "price": 30,
        "category": "Snacks",
        "description": "Burger",
      },
      {
        "id": 15,
        "image": "item15.png",
        "name": "Fries",
        "price": 30,
        "category": "Snacks",
        "description": "Fries",
      },
    ];
  }
}
